version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
      docker: 20
    commands:
      - echo Installing Maven...
      - curl -sSL https://apache.osuosl.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.zip -o maven.zip
      - unzip -q maven.zip
      - export M2_HOME=$PWD/apache-maven-3.9.6
      - export PATH=$M2_HOME/bin:$PATH
      - export JAVA_HOME=/usr/lib/jvm/java-21-amazon-corretto
      - echo "Java Home: $JAVA_HOME"
      - java -version
      - mvn -version
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 886436949122.dkr.ecr.ap-south-1.amazonaws.com)
      - echo "Setting environment variables..."
      - REPOSITORY_URI="886436949122.dkr.ecr.ap-south-1.amazonaws.com/project-management-tool"
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo "Packaging with Maven and Java 21..."
      - mvn clean package -DskipTests -Dmaven.compiler.release=21 --no-transfer-progress
  build:
    commands:
      - echo Building Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
  post_build:
    commands:
      - echo Pushing image to ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing imagedefinitions.json...
      - printf '[{"name":"project-management-tool","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
